### ISSUE TITLE
BioInsights plugin not initializing

### ISSUE THREAD

**Issue by cafuneandchill** [cerus/observatorycore-linux#2]
## Description

BioInsights plugin not working.

```
ERROR: Library '/mnt/3e9741bd-cdc0-43d0-9034-433ed3c46557/observatory-linux//plugins/ObservatoryBioInsights.dll' contains no suitable interfaces. - 
```

## Steps to reproduce

1. Install the [BioInsights plugin v0.23.35.1439 (06-Feb-2023)](https://edjp.colacube.net/observatory#plugins)
2. Launch Observatory.

## Notes

While BioInsights doesn't work, Evaluator v0.22.347.1524 (13-Dec-2022) works.

**Comment by cerus** [comment]
Just tried to reproduce this and everything seems to be working (no errors in terminal, plugin shows up in plugin list etc). The error in your issue says something about a .dll, but the plugin is a .eop file. Are you sure you've moved the correct file into the plugins folder?

**Comment by cafuneandchill** [comment]
Yeah, it seems that installing plugins using `.dll` files doesn't work, so that was a mistake on my end.
