### ISSUE TITLE
Lua parsing for Explorer custom criteria (missing lua54.so)

### ISSUE THREAD

**Issue by Silarn** [cerus/observatorycore-linux#5]
The build needs to be adjusted to capture the lua54.so file for these builds. The file is populated in the actual build but isn't copied into the packaged archive by the script.

I haven't tested it fully yet but it seems to work if this is placed in the `runtimes\linux-x64\native` directory. It may also work under `plugins\deps`, I'm not sure.

Without this, you will get error messages when attempting to parse a custom criteria lua script.

**Comment by cerus** [comment]
Thank you for reporting this issue. lua54.so will now be copied to the natives directory when running the build script.
